################################################################
#                                                              #
#    Huje22 Bds-Auto-Enable                                    #
#  https://github.com/Huje22/Bds-Auto-Enable                   #
#                                                              #
################################################################
#  
# Pierwsze uruchomienie
firstRun: false
#  
# System na którym uruchamiana jest aplikacja
systemOs: LINUX
#  
# Nazwa pliku który ma być włączony
name: bedrock_server.exe
#  
#  
filePath: ./
